### ISSUE TITLE
GhostRecon Breakpoint clan members

### ISSUE THREAD

**Issue by Lightlightingstorm** [MicrosoftDocs/azure-devops-docs#13964]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b6fa5bb-ed52-b765-c7a2-70307dbc5afa
* Version Independent ID: 86f17782-98c7-ab62-0b00-d991be8c41bf
* Content: [Manage paid access for users - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/billing/buy-basic-access-add-users?view=azure-devops#select-the-default-access-level-for-new-users)
* Content Source: [docs/organizations/billing/buy-basic-access-add-users.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/billing/buy-basic-access-add-users.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**
```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/azure-devops-docs/pull/13960
- [ ] https://github.com/MicrosoftDocs/azure-devops-docs/issues/13962
- [ ] https://github.com/MicrosoftDocs/azure-devops-docs/issues/13961
- [ ] https://github.com/MicrosoftDocs/azure-devops-docs/issues/13855
```

**Comment by Lightlightingstorm** [comment]
how to edit up date an add game part an replace games
